name: flutter_low_code
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理
  get: ^4.6.5
  # fair: ^3.0.0
  fair:
    git:
      url: https://github.com/wuba/fair.git
      ref: main
      path: fair
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  fair_compiler: ^1.5.1

dependency_overrides:
  # fair_version: ^3.0.0+2
  fair_version:
    git:
      url: https://github.com/wuba/fair.git
      ref: main
      path: flutter_version/flutter_3_3_0

assets:
    - assets/fair/
    
flutter:
  uses-material-design: true
